[package]
name = "RustySolutions"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "RustySolutions"
path = "ForAnalyzer.rs"

[dependencies]

[workspace]
members = ["src/1/1/1", "src/1/1/2", "src/1/1/3", "src/1/1/4", "src/1/1/5", "src/1/1/6", "src/1/1/7", "src/1/2/1", "src/1/2/2", "src/1/2/3"]
